repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.9.7
  hooks:
    # Run the linter.
    - id: ruff
      exclude: ^migrations/|/migrations/
      files: ^(backend|runner)/
      types_or: [ python, pyi ]
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
      files: ^(backend|runner)/
      exclude: ^migrations/|/migrations/
      types_or: [ python, pyi ]

- repo: https://github.com/astral-sh/uv-pre-commit
  # uv version.
  rev: 0.8.13
  hooks:
    # Update the uv lockfile
    - id: uv-lock
      files: backend/pyproject.toml
      args: [--project, backend]

    - id: uv-lock
      files: runner/pyproject.toml
      args: [--project, runner]

    - id: uv-export
      files: backend/pyproject.toml
      args:
        - --project=backend
        - --no-hashes
        - --output-file=backend/requirements.txt

    - id: uv-export
      files: runner/pyproject.toml
      args:
        - --project=runner
        - --no-hashes
        - --output-file=runner/requirements.txt
